# Dataset: ppax (20250721 – pPaxy118/rb647 + paxillin/m568)  |  condition: control
# Normalization: cell_insideoutside, dual-channel (ch1+ch3), no rolling ball
paths:
  root_folder      : "/home/lding/lding/fa_data_analysis"
  image_folder     : root_folder + "/fa_data/other_paxillin/20250721_eGFP-Zyxin 488_Phalloidin405_pPaxy118(rb) 647_Pax(m)568/Control"
  cell_mask_folder : null
  patch_output_dir : root_folder + "/ae_results/other_paxillin/patches_dualch_cio/ppax/control/tiff_patches32"
  plot_output_dir  : root_folder + "/ae_results/other_paxillin/patches_dualch_cio/ppax/control/plot_patches32"
experiment:
  condition : "control"
  channels  : [1, 3]
input:
  file_type : "czi"
  start_ind : 0
  end_ind   : 999
patch:
  patch_size   : 32
  mask_ratio   : 0.4
  pad_size     : 64
  patch_prefix : "control"
preprocessing:
  rolling_ball_radius : null
normalization:
  norm_mode : "cell_insideoutside"
segmentation:
  seg_ch                  : 3
  seg_threshold           : 0.2
  seg_close_size          : 5
  seg_min_size_initial    : 3
  seg_min_size_post_close : 10
  seg_min_size_final      : 30000
augmentation:
  rand_trans    : false
  max_shift_px  : 0
  rand_rota     : false
  max_angle_deg : 0.0
misc:
  dpi           : 256
  debug         : false
  log_level     : "INFO"
  use_timestamp : false
