# =============================================================================
# Visualization: AE: semicon_fa | Features: latent 8-dim only
# Results: results/test_run_cio/semicon_fa/vis_lat8/
# =============================================================================
root_folder : "/home/lding/lding/fa_data_analysis"
input:
  latents_csv          : root_folder + "/ae_results/test_run_cio/semicon_fa/latents.csv"
  fa_type_results_csv  : root_folder + "/ae_results/test_run_cio/semicon_fa/fa_cls_lat8/predictions_all.csv"
  position_results_csv : root_folder + "/ae_results/test_run_cio/semicon_fa/pos_cls_lat8/predictions_all.csv"
  umap_model_pkl       : root_folder + "/ae_results/test_run_cio/semicon_fa/fa_cls_lat8/umap_all_model.pkl"

output:
  out_dir : root_folder + "/ae_results/test_run_cio/semicon_fa/vis_lat8"

labels:
  fa_type_label_col  : "classification"
  position_label_col : "Position"
  fa_type_order:
    - "Nascent Adhesion"
    - "focal complex"
    - "focal adhesion"
    - "fibrillar adhesion"
    - "No adhesion"
  position_order:
    - "Cell Protruding Edge"
    - "Cell Periphery/other"
    - "Lamella"
    - "Cell Body"

misc:
  random_state : 42
  log_level    : "INFO"
