root_folder : "/home/lding/lding/fa_data_analysis"

input:
  latents_csv          : root_folder + "/ae_results/contrastive_run/contrastive_cio_rb_vinc_lat12proj8/latents.csv"
  fa_type_results_csv  : root_folder + "/ae_results/contrastive_run/contrastive_cio_rb_vinc_lat12proj8/fa_cls_zrecon/predictions_all.csv"
  position_results_csv : root_folder + "/ae_results/contrastive_run/contrastive_cio_rb_vinc_lat12proj8/pos_cls_zrecon/predictions_all.csv"
  umap_model_pkl       : root_folder + "/ae_results/contrastive_run/contrastive_cio_rb_vinc_lat12proj8/fa_cls_zrecon/umap_all_model.pkl"

output:
  out_dir : root_folder + "/ae_results/contrastive_run/contrastive_cio_rb_vinc_lat12proj8/vis_zrecon"

labels:
  fa_type_label_col  : "classification"
  position_label_col : "Position"
  fa_type_order:
    - "Nascent Adhesion"
    - "focal complex"
    - "focal adhesion"
    - "fibrillar adhesion"
    - "No adhesion"
  position_order:
    - "Cell Protruding Edge"
    - "Cell Periphery/other"
    - "Lamella"
    - "Cell Body"

misc:
  random_state : 42
  log_level    : "INFO"
