# Cls Apply: Position | semisup_pos | lat8 | dataset: nih3t3
root_folder : "/home/lding/lding/fa_data_analysis"
input:
  latents_csv : "/home/lding/lding/fa_data_analysis/ae_results/other_paxillin/semisup_pos/nih3t3/latents_newdata.csv"

model:
  model_pkl      : "/home/lding/lding/fa_data_analysis/ae_results/test_run_overfit_20260322/semisup_pos/pos_cls_lat8/lgbm_model.pkl"
  umap_model_pkl : "/home/lding/lding/fa_data_analysis/ae_results/test_run_overfit_20260322/semisup_pos/pos_cls_lat8/umap_all_model.pkl"

output:
  out_dir : "/home/lding/lding/fa_data_analysis/ae_results/other_paxillin/semisup_pos/nih3t3/pos_cls_lat8"

labels:
  label_order:
    - "Cell Protruding Edge"
    - "Cell Periphery/other"
    - "Lamella"
    - "Cell Body"

features:
  feature_cols : null

dist_features:
  patch_prep_dirs: null
  feature_weight : 20.0

misc:
  log_level : "INFO"
